import type { ScreenMode, ScreenProfile, TerminalSettings } from '../core/profile.js';
import { COLOR_PROFILES, type ColorProfileId } from '../core/color-profiles.js';

export type PresetControlState = { name: string; draftName: string; dirty: boolean };

export function DisplaySettingsSection({ value, modes, onChange }: { value: ScreenProfile; modes: readonly ScreenMode[]; onChange: (value: ScreenProfile) => void }) {
  return <>{modes.length > 1 && <label className="resolution-control">Virtual resolution<select value={value.virtualScreen.modeId} onChange={(event) => onChange({ ...value, virtualScreen: { modeId: event.target.value } })}>{modes.map((mode) => <option key={mode.id} value={mode.id}>{mode.label ?? mode.id}</option>)}</select></label>}</>;
}

export function TerminalSettingsSection({ value, fonts, onChange }: { value: ScreenProfile; fonts: readonly string[]; onChange: (value: ScreenProfile) => void }) {
  const update = (patch: Partial<TerminalSettings>) => onChange({ ...value, terminal: { ...value.terminal, ...patch } });
  return <fieldset className="screen-section terminal-section"><legend>Terminal</legend><label className="resolution-control">ANSI color profile<select value={value.terminal.colorProfile} onChange={(event) => update({ colorProfile: event.target.value as ColorProfileId })}>{COLOR_PROFILES.map((profile) => <option key={profile.id} value={profile.id}>{profile.label}</option>)}</select></label><label className="resolution-control">Console font<select value={value.terminal.fontFamily} onChange={(event) => update({ fontFamily: event.target.value })}>{!fonts.includes(value.terminal.fontFamily) && <option value={value.terminal.fontFamily}>{value.terminal.fontFamily}</option>}{fonts.map((font) => <option key={font} value={font}>{font}</option>)}</select></label><div className="font-control-row"><label className="resolution-control">Size<input type="number" min={6} max={32} value={value.terminal.fontSize} onChange={(event) => update({ fontSize: Math.max(6, Math.min(32, Number(event.target.value))) })} /></label><label className="resolution-control">Cell width ±px<input type="number" min={-8} max={16} value={value.terminal.cellWidthAdjustment} onChange={(event) => update({ cellWidthAdjustment: Number(event.target.value) })} /></label><label className="resolution-control">Cell height ±px<input type="number" min={-8} max={16} value={value.terminal.cellHeightAdjustment} onChange={(event) => update({ cellHeightAdjustment: Number(event.target.value) })} /></label></div><div className="setting-block"><span className="setting-label">Cursor style</span>{(['block', 'underline', 'bar'] as const).map((cursorStyle) => <button type="button" key={cursorStyle} onClick={() => update({ cursorStyle })}>{cursorStyle}</button>)}</div></fieldset>;
}

export function CRTSettingsSection({ value, onChange }: { value: ScreenProfile; onChange: (value: ScreenProfile) => void }) {
  const update = (patch: Partial<ScreenProfile['crt']>) => onChange({ ...value, crt: { ...value.crt, ...patch } });
  return <fieldset className="screen-section crt-section"><legend>CRT</legend><label className="switch-control"><span className="switch-label">CRT Emulation</span><input type="checkbox" checked={value.crt.crtEmulation} onChange={(event) => update({ crtEmulation: event.target.checked })} /></label><label className="resolution-control">Color mode<select value={value.crt.colorMode} onChange={(event) => update({ colorMode: event.target.value as ScreenProfile['crt']['colorMode'] })}><option value="color">Color</option><option value="bw">B&amp;W</option><option value="green">Green (P31)</option><option value="green-p39">Green (P39)</option><option value="amber">Amber</option><option value="blue">Phosphor Blue</option></select></label><label className="slider-control"><span>Curvature<output>{value.crt.curvature}</output></span><input type="range" min="0" max="0.5" step="0.01" value={value.crt.curvature} onChange={(event) => update({ curvature: Number(event.target.value) })} /></label><label className="slider-control"><span>Bloom<output>{value.crt.bloom}</output></span><input type="range" min="0" max="1" step="0.05" value={value.crt.bloom} onChange={(event) => update({ bloom: Number(event.target.value) })} /></label></fieldset>;
}

export function PresetSettingsSection({ value, names, disabled = false, onNameChange, onLoad, onSave }: { value: PresetControlState | null; names: readonly string[]; disabled?: boolean; onNameChange: (name: string) => void; onLoad: (name: string) => void; onSave: (name: string) => void }) {
  return <fieldset className="preset-controls" disabled={disabled}><legend>Presets</legend><div className="preset-picker-row"><input value={value?.draftName ?? ''} placeholder="Preset name" aria-label="Preset name" onChange={(event) => onNameChange(event.target.value)} /><button type="button" data-testid="preset-save" disabled={!value || (!value.dirty && value.draftName === value.name)} onClick={() => value && onSave(value.draftName)}>Save</button></div><label className="preset-load-control"><select aria-label="Load preset" defaultValue="" onChange={(event) => { const name = event.target.value; event.currentTarget.value = ''; if (name) onLoad(name); }}><option value="" disabled>Load preset…</option>{names.map((name) => <option key={name} value={name}>{name}</option>)}</select></label></fieldset>;
}
